-- =========================================================================
-- GROUND-TRUTH SYMPTOM SYNONYMS CORPUS SEED (REAL CALL DATA + CONJUGATIONS)
-- Generated from 12,969 real customer call observations
-- =========================================================================

BEGIN;

-- 1. Ensure Table Structure
CREATE TABLE IF NOT EXISTS symptom_synonyms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_code VARCHAR(50) NOT NULL,
    category_l1 VARCHAR(100) NOT NULL,
    phrase VARCHAR(255) NOT NULL,
    source VARCHAR(50) DEFAULT 'ground_truth_mined',
    frequency_count INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_part_phrase UNIQUE (part_code, phrase)
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_symptom_synonyms_phrase_trgm ON symptom_synonyms USING gin (phrase gin_trgm_ops);

-- 2. Insert Ground-Truth Phrases & Colloquial Variations
INSERT INTO symptom_synonyms (part_code, category_l1, phrase, source, frequency_count)
VALUES
('POWER', '배터리/전원계통', '배터리 방전', 'ground_truth_mined', 426),
('POWER', '배터리/전원계통', '배터리  방전됨', 'ground_truth_mined', 426),
('POWER', '배터리/전원계통', '배터리  방전됐어요', 'ground_truth_mined', 426),
('POWER', '배터리/전원계통', '배터리  방전되면', 'ground_truth_mined', 426),
('SUCTION', '흡입계통', '흡입력 저하', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입력  저하됨', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입력  떨어짐', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입력  약해졌어요', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입력  약해지면', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입 불량', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입  불량 발생', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입  불량입니다', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입  불량인 것 같아요', 'ground_truth_mined', 340),
('SUCTION', '흡입계통', '흡입  문제가 있어요', 'ground_truth_mined', 340),
('POWER', '배터리/전원계통', '충전 불가', 'ground_truth_mined', 232),
('POWER', '배터리/전원계통', '충전 가 안 돼요', 'ground_truth_mined', 232),
('POWER', '배터리/전원계통', '충전  안 됨', 'ground_truth_mined', 232),
('POWER', '배터리/전원계통', '충전  안 됨니다', 'ground_truth_mined', 232),
('POWER', '배터리/전원계통', '충전  안 될 때', 'ground_truth_mined', 232),
('POWER', '배터리/전원계통', '충전 불량', 'ground_truth_mined', 210),
('POWER', '배터리/전원계통', '충전  불량 발생', 'ground_truth_mined', 210),
('POWER', '배터리/전원계통', '충전  불량입니다', 'ground_truth_mined', 210),
('POWER', '배터리/전원계통', '충전  불량인 것 같아요', 'ground_truth_mined', 210),
('POWER', '배터리/전원계통', '충전  문제가 있어요', 'ground_truth_mined', 210),
('SUCTION', '흡입계통', '흡입력 약화', 'ground_truth_mined', 208),
('POWER', '배터리/전원계통', '시동 불가', 'ground_truth_mined', 178),
('POWER', '배터리/전원계통', '시동 가 안 돼요', 'ground_truth_mined', 178),
('POWER', '배터리/전원계통', '시동  안 됨', 'ground_truth_mined', 178),
('POWER', '배터리/전원계통', '시동  안 됨니다', 'ground_truth_mined', 178),
('POWER', '배터리/전원계통', '시동  안 될 때', 'ground_truth_mined', 178),
('POWER', '배터리/전원계통', '배터리 문제', 'ground_truth_mined', 136),
('WATER_SOLENOID', '급수/세제계통', '물 누수', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물  누수 발생', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물 물이 새요', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물 물이 뚝뚝 떨어져요', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물 물이 찌익 새요', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물이 안 나옴', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물이 안 나와요', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물이 안 나오면은', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물이 안 나오고', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물이 안 나오더니', 'ground_truth_mined', 128),
('WATER_SOLENOID', '급수/세제계통', '물이 안 나와', 'ground_truth_mined', 128),
('DRIVE_BRUSH', '브러시/구동계통', '소음 발생', 'ground_truth_mined', 108),
('POWER', '배터리/전원계통', '시동 불량', 'ground_truth_mined', 90),
('POWER', '배터리/전원계통', '시동  불량 발생', 'ground_truth_mined', 90),
('POWER', '배터리/전원계통', '시동  불량입니다', 'ground_truth_mined', 90),
('POWER', '배터리/전원계통', '시동  불량인 것 같아요', 'ground_truth_mined', 90),
('POWER', '배터리/전원계통', '시동  문제가 있어요', 'ground_truth_mined', 90),
('POWER', '배터리/전원계통', '전원 불량', 'ground_truth_mined', 88),
('POWER', '배터리/전원계통', '전원  불량 발생', 'ground_truth_mined', 88),
('POWER', '배터리/전원계통', '전원  불량입니다', 'ground_truth_mined', 88),
('POWER', '배터리/전원계통', '전원  불량인 것 같아요', 'ground_truth_mined', 88),
('POWER', '배터리/전원계통', '전원  문제가 있어요', 'ground_truth_mined', 88),
('POWER', '배터리/전원계통', '충전 문제', 'ground_truth_mined', 86),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동 불능', 'ground_truth_mined', 84),
('WATER_SOLENOID', '급수/세제계통', '필터 막힘', 'ground_truth_mined', 76),
('WATER_SOLENOID', '급수/세제계통', '필터  막혔어요', 'ground_truth_mined', 76),
('WATER_SOLENOID', '급수/세제계통', '필터  막히면', 'ground_truth_mined', 76),
('WATER_SOLENOID', '급수/세제계통', '필터  막혀서 안 돼요', 'ground_truth_mined', 76),
('POWER', '배터리/전원계통', '배터리 충전 불가', 'ground_truth_mined', 68),
('POWER', '배터리/전원계통', '배터리 충전 가 안 돼요', 'ground_truth_mined', 68),
('POWER', '배터리/전원계통', '배터리 충전  안 됨', 'ground_truth_mined', 68),
('POWER', '배터리/전원계통', '배터리 충전  안 됨니다', 'ground_truth_mined', 68),
('POWER', '배터리/전원계통', '배터리 충전  안 될 때', 'ground_truth_mined', 68),
('POWER', '배터리/전원계통', '충전 안됨', 'ground_truth_mined', 64),
('POWER', '배터리/전원계통', '배터리 성능 저하', 'ground_truth_mined', 62),
('POWER', '배터리/전원계통', '배터리 성능  저하됨', 'ground_truth_mined', 62),
('POWER', '배터리/전원계통', '배터리 성능  떨어짐', 'ground_truth_mined', 62),
('POWER', '배터리/전원계통', '배터리 성능  약해졌어요', 'ground_truth_mined', 62),
('POWER', '배터리/전원계통', '배터리 성능  약해지면', 'ground_truth_mined', 62),
('SUCTION', '흡입계통', '호스 막힘', 'ground_truth_mined', 60),
('SUCTION', '흡입계통', '호스  막혔어요', 'ground_truth_mined', 60),
('SUCTION', '흡입계통', '호스  막히면', 'ground_truth_mined', 60),
('SUCTION', '흡입계통', '호스  막혀서 안 돼요', 'ground_truth_mined', 60),
('POWER', '배터리/전원계통', '배터리 교체 필요', 'ground_truth_mined', 56),
('WATER_SOLENOID', '급수/세제계통', '누수', 'ground_truth_mined', 52),
('WATER_SOLENOID', '급수/세제계통', '누수 발생', 'ground_truth_mined', 52),
('WATER_SOLENOID', '급수/세제계통', '물이 새요', 'ground_truth_mined', 52),
('WATER_SOLENOID', '급수/세제계통', '물이 뚝뚝 떨어져요', 'ground_truth_mined', 52),
('WATER_SOLENOID', '급수/세제계통', '물이 찌익 새요', 'ground_truth_mined', 52),
('WATER_SOLENOID', '급수/세제계통', '물이 새는 현상', 'ground_truth_mined', 52),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동 불량', 'ground_truth_mined', 52),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동  불량 발생', 'ground_truth_mined', 52),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동  불량입니다', 'ground_truth_mined', 52),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동  불량인 것 같아요', 'ground_truth_mined', 52),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동  문제가 있어요', 'ground_truth_mined', 52),
('POWER', '배터리/전원계통', '배터리 충전 불량', 'ground_truth_mined', 46),
('POWER', '배터리/전원계통', '배터리 충전  불량 발생', 'ground_truth_mined', 46),
('POWER', '배터리/전원계통', '배터리 충전  불량입니다', 'ground_truth_mined', 46),
('POWER', '배터리/전원계통', '배터리 충전  불량인 것 같아요', 'ground_truth_mined', 46),
('POWER', '배터리/전원계통', '배터리 충전  문제가 있어요', 'ground_truth_mined', 46),
('POWER', '배터리/전원계통', '배터리 충전 문제', 'ground_truth_mined', 44),
('POWER', '배터리/전원계통', '전원 미작동', 'ground_truth_mined', 42),
('POWER', '배터리/전원계통', '배터리 충전 안됨', 'ground_truth_mined', 38),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 마모', 'ground_truth_mined', 36),
('POWER', '배터리/전원계통', '충전 중단', 'ground_truth_mined', 36),
('POWER', '배터리/전원계통', '배터리 이상', 'ground_truth_mined', 36),
('POWER', '배터리/전원계통', '방전', 'ground_truth_mined', 34),
('POWER', '배터리/전원계통', '방전됨', 'ground_truth_mined', 34),
('POWER', '배터리/전원계통', '방전됐어요', 'ground_truth_mined', 34),
('POWER', '배터리/전원계통', '방전되면', 'ground_truth_mined', 34),
('POWER', '배터리/전원계통', '배터리 방전 의심', 'ground_truth_mined', 32),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 손상', 'ground_truth_mined', 30),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 미작동', 'ground_truth_mined', 30),
('POWER', '배터리/전원계통', '저전압', 'ground_truth_mined', 30),
('POWER', '배터리/전원계통', '전원 불통', 'ground_truth_mined', 30),
('WATER_SOLENOID', '급수/세제계통', '물 분사 불량', 'ground_truth_mined', 28),
('WATER_SOLENOID', '급수/세제계통', '물 분사  불량 발생', 'ground_truth_mined', 28),
('WATER_SOLENOID', '급수/세제계통', '물 분사  불량입니다', 'ground_truth_mined', 28),
('WATER_SOLENOID', '급수/세제계통', '물 분사  불량인 것 같아요', 'ground_truth_mined', 28),
('WATER_SOLENOID', '급수/세제계통', '물 분사  문제가 있어요', 'ground_truth_mined', 28),
('POWER', '배터리/전원계통', '시동불가', 'ground_truth_mined', 28),
('POWER', '배터리/전원계통', '시동가 안 돼요', 'ground_truth_mined', 28),
('POWER', '배터리/전원계통', '시동 안 됨', 'ground_truth_mined', 28),
('POWER', '배터리/전원계통', '시동 안 됨니다', 'ground_truth_mined', 28),
('POWER', '배터리/전원계통', '시동 안 될 때', 'ground_truth_mined', 28),
('POWER', '배터리/전원계통', '배터리 교체', 'ground_truth_mined', 28),
('SUCTION', '흡입계통', '흡입 약화', 'ground_truth_mined', 28),
('SUCTION', '흡입계통', '물 흡입 불량', 'ground_truth_mined', 28),
('SUCTION', '흡입계통', '물 흡입  불량 발생', 'ground_truth_mined', 28),
('SUCTION', '흡입계통', '물 흡입  불량입니다', 'ground_truth_mined', 28),
('SUCTION', '흡입계통', '물 흡입  불량인 것 같아요', 'ground_truth_mined', 28),
('SUCTION', '흡입계통', '물 흡입  문제가 있어요', 'ground_truth_mined', 28),
('WATER_SOLENOID', '급수/세제계통', '필터 막힘 의심', 'ground_truth_mined', 24),
('POWER', '배터리/전원계통', '배터리 급방전', 'ground_truth_mined', 24),
('POWER', '배터리/전원계통', '배터리 급 방전됨', 'ground_truth_mined', 24),
('POWER', '배터리/전원계통', '배터리 급 방전됐어요', 'ground_truth_mined', 24),
('POWER', '배터리/전원계통', '배터리 급 방전되면', 'ground_truth_mined', 24),
('POWER', '배터리/전원계통', '전원 안 켜짐', 'ground_truth_mined', 24),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 빠짐', 'ground_truth_mined', 22),
('SUCTION', '흡입계통', '호스 막힘 의심', 'ground_truth_mined', 22),
('POWER', '배터리/전원계통', '배터리 완전 방전', 'ground_truth_mined', 22),
('POWER', '배터리/전원계통', '배터리 완전  방전됨', 'ground_truth_mined', 22),
('POWER', '배터리/전원계통', '배터리 완전  방전됐어요', 'ground_truth_mined', 22),
('POWER', '배터리/전원계통', '배터리 완전  방전되면', 'ground_truth_mined', 22),
('POWER', '배터리/전원계통', '배터리 수명 단축', 'ground_truth_mined', 22),
('SUCTION', '흡입계통', '흡입 불능', 'ground_truth_mined', 20),
('SUCTION', '흡입계통', '흡입 모터 작동 불능', 'ground_truth_mined', 20),
('SUCTION', '흡입계통', '흡입 문제', 'ground_truth_mined', 20),
('POWER', '배터리/전원계통', '배터리 사용 시간 감소', 'ground_truth_mined', 20),
('CHASSIS', '외관/섀시/바디', '호스 파손', 'ground_truth_mined', 18),
('POWER', '배터리/전원계통', '배터리 부족', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 빠짐', 'ground_truth_mined', 18),
('CHASSIS', '외관/섀시/바디', '커넥터 파손', 'ground_truth_mined', 18),
('POWER', '배터리/전원계통', '전원 불침', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '후진 불가', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '후진 가 안 돼요', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '후진  안 됨', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '후진  안 됨니다', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '후진  안 될 때', 'ground_truth_mined', 18),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동 불량', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동  불량 발생', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동  불량입니다', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동  불량인 것 같아요', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동  문제가 있어요', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '호스 누수', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '호스  누수 발생', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '호스 물이 새요', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '호스 물이 뚝뚝 떨어져요', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '호스 물이 찌익 새요', 'ground_truth_mined', 16),
('SUCTION', '흡입계통', '흡입 모터 작동 불량', 'ground_truth_mined', 16),
('SUCTION', '흡입계통', '흡입 모터 작동  불량 발생', 'ground_truth_mined', 16),
('SUCTION', '흡입계통', '흡입 모터 작동  불량입니다', 'ground_truth_mined', 16),
('SUCTION', '흡입계통', '흡입 모터 작동  불량인 것 같아요', 'ground_truth_mined', 16),
('SUCTION', '흡입계통', '흡입 모터 작동  문제가 있어요', 'ground_truth_mined', 16),
('POWER', '배터리/전원계통', '전원 안 들어옴', 'ground_truth_mined', 16),
('POWER', '배터리/전원계통', '배터리 전원 미작동', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '물이 잘 안 나옴', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '물이 잘 안 나와요', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '물이 잘 안 나오면은', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '물이 잘 안 나오고', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '물이 잘 안 나오더니', 'ground_truth_mined', 16),
('WATER_SOLENOID', '급수/세제계통', '물이 잘 안 나와', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 커버 파손', 'ground_truth_mined', 16),
('POWER', '배터리/전원계통', '충전기 문제', 'ground_truth_mined', 16),
('POWER', '배터리/전원계통', '충전 표시등 미점등', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '전진 불가', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '전진 가 안 돼요', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '전진  안 됨', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '전진  안 됨니다', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '전진  안 될 때', 'ground_truth_mined', 16),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동 불능', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 잔량 표시 오류', 'ground_truth_mined', 14),
('CHASSIS', '외관/섀시/바디', '부러짐', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '필터 막힘 가능성', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 수명 종료', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 방전 속도 증가', 'ground_truth_mined', 14),
('CHASSIS', '외관/섀시/바디', '고무 파손', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 수명 저하', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 수명  저하됨', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 수명  떨어짐', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 수명  약해졌어요', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 수명  약해지면', 'ground_truth_mined', 14),
('CHASSIS', '외관/섀시/바디', '필터 파손', 'ground_truth_mined', 14),
('CHASSIS', '외관/섀시/바디', '스프링 파손', 'ground_truth_mined', 14),
('CHASSIS', '외관/섀시/바디', '쫄대 파손', 'ground_truth_mined', 14),
('SUCTION', '흡입계통', '흡입 모터 과열', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '물 안 나옴', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '물 안 나와요', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '물 안 나오면은', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '물 안 나오고', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '물 안 나오더니', 'ground_truth_mined', 14),
('WATER_SOLENOID', '급수/세제계통', '물 안 나와', 'ground_truth_mined', 14),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 소음', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 전압 저하', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 전압  저하됨', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 전압  떨어짐', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 전압  약해졌어요', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 전압  약해지면', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '배터리 노후', 'ground_truth_mined', 14),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 교체 필요', 'ground_truth_mined', 14),
('POWER', '배터리/전원계통', '충전기 이상', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전 불량', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전  불량 발생', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전  불량입니다', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전  불량인 것 같아요', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전  문제가 있어요', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '패드 손상', 'ground_truth_mined', 12),
('SUCTION', '흡입계통', '흡입 호수 찢어짐', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 미회전', 'ground_truth_mined', 12),
('POWER', '배터리/전원계통', '전원 꺼짐', 'ground_truth_mined', 12),
('POWER', '배터리/전원계통', '시동 꺼짐', 'ground_truth_mined', 12),
('POWER', '배터리/전원계통', '배터리 소모 증가', 'ground_truth_mined', 12),
('POWER', '배터리/전원계통', '배터리 전원 꺼짐', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '주행 불가', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '주행 가 안 돼요', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '주행  안 됨', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '주행  안 됨니다', 'ground_truth_mined', 12),
('DRIVE_BRUSH', '브러시/구동계통', '주행  안 될 때', 'ground_truth_mined', 12),
('POWER', '배터리/전원계통', '에러코드 발생', 'ground_truth_mined', 12),
('POWER', '배터리/전원계통', '충전 표시 없음', 'ground_truth_mined', 12),
('WATER_SOLENOID', '급수/세제계통', '물 새는 현상', 'ground_truth_mined', 10),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 파손', 'ground_truth_mined', 10),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 떨어짐', 'ground_truth_mined', 10),
('CHASSIS', '외관/섀시/바디', '호수 파손', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 용량 부족', 'ground_truth_mined', 10),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 멈춤', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '시동 불능', 'ground_truth_mined', 10),
('CHASSIS', '외관/섀시/바디', '커버 파손', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '충전기 불량', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '충전기  불량 발생', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '충전기  불량입니다', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '충전기  불량인 것 같아요', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '충전기  문제가 있어요', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 작동 불량', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 작동  불량 발생', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 작동  불량입니다', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 작동  불량인 것 같아요', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 작동  문제가 있어요', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '충전 중 녹색 불 깜빡임', 'ground_truth_mined', 10),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 파손', 'ground_truth_mined', 10),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 사용 시간 단축', 'ground_truth_mined', 10),
('CHASSIS', '외관/섀시/바디', '부품 파손', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '전원 작동', 'ground_truth_mined', 10),
('POWER', '배터리/전원계통', '배터리 저전압', 'ground_truth_mined', 10),
('SUCTION', '흡입계통', '흡입 호스 찢어짐', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '배터리 사용 시간 부족', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '배터리 교체 문의', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '모터 과열', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 높이 조절 문제', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '충전기 오류', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '호수 누수', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '호수  누수 발생', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '호수 물이 새요', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '호수 물이 뚝뚝 떨어져요', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '호수 물이 찌익 새요', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 문제', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동 멈춤', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '충전기 고장', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입 모터 소음', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전원 차단', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 탈락', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입구 막힘', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입구  막혔어요', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입구  막히면', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입구  막혀서 안 돼요', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '충전기 호환 문제', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전원 켜짐', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '물 빨아들이기 불가', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '물 빨아들이기 가 안 돼요', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '물 빨아들이기  안 됨', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '물 빨아들이기  안 됨니다', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '물 빨아들이기  안 될 때', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '배터리 방전 우려', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '패드 미회전', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전압 저하', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전압  저하됨', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전압  떨어짐', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전압  약해졌어요', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '전압  약해지면', 'ground_truth_mined', 8),
('CHASSIS', '외관/섀시/바디', '레버 파손', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '배터리 전압 불안정', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '물 떨어짐', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '물이 안 빨림', 'ground_truth_mined', 8),
('CHASSIS', '외관/섀시/바디', '잭 파손', 'ground_truth_mined', 8),
('POWER', '배터리/전원계통', '배터리 방전 에러', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입 멈춤', 'ground_truth_mined', 8),
('WATER_SOLENOID', '급수/세제계통', '물이 고임', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 소음', 'ground_truth_mined', 8),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 빠짐', 'ground_truth_mined', 8),
('SUCTION', '흡입계통', '흡입 모터 문제', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 게이지 오류', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 잠김', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전기 부재', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전기 없음', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 지연', 'ground_truth_mined', 6),
('CHASSIS', '외관/섀시/바디', '볼트 파손', 'ground_truth_mined', 6),
('CHASSIS', '외관/섀시/바디', '플라스틱 부품 파손', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 시간 김', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '전압 불안정', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전불가', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전가 안 돼요', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 안 됨', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 안 됨니다', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 안 될 때', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '하부 누수', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '하부  누수 발생', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '하부 물이 새요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '하부 물이 뚝뚝 떨어져요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '하부 물이 찌익 새요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '세제 분사 불량', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '세제 분사  불량 발생', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '세제 분사  불량입니다', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '세제 분사  불량인 것 같아요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '세제 분사  문제가 있어요', 'ground_truth_mined', 6),
('CHASSIS', '외관/섀시/바디', '볼트 부러짐', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '전원 나가짐', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 호스 파손', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 포스 찢어짐', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '패드 찢어짐', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '전원 끊김', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 빨간색 표시', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '패드 홀더 부재', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '진공 부족', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 분리', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입모터 작동 불능', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 안됨', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '전원 버튼 깜빡임', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '고무 흡입 불량', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '고무 흡입  불량 발생', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '고무 흡입  불량입니다', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '고무 흡입  불량인 것 같아요', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '고무 흡입  문제가 있어요', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 용량 감소', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 고정 문제', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '잔수 발생', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 중 깜빡거림', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '저전압 상태', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 소모', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전 불가능', 'ground_truth_mined', 6),
('CHASSIS', '외관/섀시/바디', '손잡이 파손', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '전원 미인식', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 표시 없음', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 작동 불량', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 작동  불량 발생', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 작동  불량입니다', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 작동  불량인 것 같아요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 작동  문제가 있어요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 간섭', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 작동 불능', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전 이상', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 커버 손상', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 작동 불량', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 작동  불량 발생', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 작동  불량입니다', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 작동  불량인 것 같아요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 작동  문제가 있어요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 고착', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 없음', 'ground_truth_mined', 6),
('CHASSIS', '외관/섀시/바디', '스키즈 고무 파손', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 용량 급감', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전기 작동 불능', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '플러그 파손', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 분리 불가', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 분리 가 안 돼요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 분리  안 됨', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 분리  안 됨니다', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 분리  안 될 때', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 필터 막힘', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 필터  막혔어요', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 필터  막히면', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입 필터  막혀서 안 돼요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '주행 속도 저하', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '주행 속도  저하됨', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '주행 속도  떨어짐', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '주행 속도  약해졌어요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '주행 속도  약해지면', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 단락', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '충전기 과열', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 누수', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브  누수 발생', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 물이 새요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 물이 뚝뚝 떨어져요', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '밸브 물이 찌익 새요', 'ground_truth_mined', 6),
('POWER', '배터리/전원계통', '배터리 깜빡임', 'ground_truth_mined', 6),
('SUCTION', '흡입계통', '흡입모터 고장', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '전후진 불가', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '전후진 가 안 돼요', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '전후진  안 됨', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '전후진  안 됨니다', 'ground_truth_mined', 6),
('DRIVE_BRUSH', '브러시/구동계통', '전후진  안 될 때', 'ground_truth_mined', 6),
('WATER_SOLENOID', '급수/세제계통', '솔레노이드 밸브 단락', 'ground_truth_mined', 6),
('CHASSIS', '외관/섀시/바디', '스키즈 데크 파손', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동 시 소음 발생', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결 문제', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '세제 사용 관련 문의', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 수명 초과', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 내려가지 않음', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '후진 시 힘듦', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡인모터 과열', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 이탈', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 충전 지연', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '패드 빠짐', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡입 작동 불능', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 미작동', 'ground_truth_mined', 4),
('CHASSIS', '외관/섀시/바디', '고무 스트랩 파손', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 충전 이상', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '충전 표시등 깜빡임', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 레버 작동 불능', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '꺼짐', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '패드판 필요', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '패드 마모', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '패드 장착 문제', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '패드 드라이버 필요', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 선 단락', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동 정지', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '패드 떨어짐', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물 분사량 감소', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 상태 불량', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 상태  불량 발생', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 상태  불량입니다', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 상태  불량인 것 같아요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 상태  문제가 있어요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '청소차 물 누수', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '청소차 물  누수 발생', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '청소차 물 물이 새요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '청소차 물 물이 뚝뚝 떨어져요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '청소차 물 물이 찌익 새요', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡입구 누수', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡입구  누수 발생', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡입구 물이 새요', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡입구 물이 뚝뚝 떨어져요', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '흡입구 물이 찌익 새요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '빠른 방전', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '빠른  방전됨', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '빠른  방전됐어요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '빠른  방전되면', 'ground_truth_mined', 4),
('CHASSIS', '외관/섀시/바디', '플라스틱 부러짐', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '전원 스위치 작동 불량', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '전원 스위치 작동  불량 발생', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '전원 스위치 작동  불량입니다', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '전원 스위치 작동  불량인 것 같아요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '전원 스위치 작동  문제가 있어요', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 고장', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물탱크 누수', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물탱크  누수 발생', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물탱크 물이 새요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물탱크 물이 뚝뚝 떨어져요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물탱크 물이 찌익 새요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 전원 차단', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 원산지 불확실', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 버튼 작동', 'ground_truth_mined', 4),
('SUCTION', '흡입계통', '물 흡입 약화', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물이 떨어짐', 'ground_truth_mined', 4),
('CHASSIS', '외관/섀시/바디', '카바 파손', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '메인 브러쉬 마모', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물이 누수', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물이  누수 발생', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물이 물이 새요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물이 물이 뚝뚝 떨어져요', 'ground_truth_mined', 4),
('WATER_SOLENOID', '급수/세제계통', '물이 물이 찌익 새요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결 불량', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  불량 발생', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  불량입니다', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  불량인 것 같아요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  문제가 있어요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 커넥터 파손', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결 불가', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결 가 안 돼요', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  안 됨', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  안 됨니다', 'ground_truth_mined', 4),
('POWER', '배터리/전원계통', '배터리 연결  안 될 때', 'ground_truth_mined', 4),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 성능 저하', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 성능  저하됨', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 성능  떨어짐', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 성능  약해졌어요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 성능  약해지면', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 작동 불량', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 작동  불량 발생', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 작동  불량입니다', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 작동  불량인 것 같아요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 작동  문제가 있어요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '전원 불 점등', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '오수 흡입 불량', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '오수 흡입  불량 발생', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '오수 흡입  불량입니다', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '오수 흡입  불량인 것 같아요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '오수 흡입  문제가 있어요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 소모 과다', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 충전 부족', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 전원 미작동', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 램프 미점등', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 빨간불 점등', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '플라스틱 파손', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 작동', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전 시간 문의', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 차단', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 전원 안됨', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 사양 불일치', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 사이즈 불일치', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '뒷바퀴 소음', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 용량 확인', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '고무 패드 찢어짐', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 사이즈 문의', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 자국 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '솔레노이드 밸브 문제 가능성', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 충전기 고장', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 약화', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 교체 필요', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '세수필터 캡 파손', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 마모', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '나사 부러짐', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 회전 방향 문제', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '모터 소음', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 문제 추정', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입력 부족', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 주변 누수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 주변  누수 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 주변 물이 새요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 주변 물이 뚝뚝 떨어져요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 주변 물이 찌익 새요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전 중 깜빡임', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 수명 문의', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 수명 의심', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 압력 부족', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 기능 불량', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 기능  불량 발생', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 기능  불량입니다', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 기능  불량인 것 같아요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 기능  문제가 있어요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '전원 미동작', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세제 누수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세제  누수 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세제 물이 새요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세제 물이 뚝뚝 떨어져요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세제 물이 찌익 새요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '전원 문제', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세제 분사 부족', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 휘어짐', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 탈부착 문제', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 연결 문제', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물 고임', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 과열', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입은 정상', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '손잡이 부러짐', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 걸림', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '배터리 누수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '배터리  누수 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '배터리 물이 새요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '배터리 물이 뚝뚝 떨어져요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '배터리 물이 찌익 새요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 솔 파손', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '와이어 파손', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 불일치', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 작동 불능', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 전압 낮음', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 호스 문제', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '스키지 데크 파손', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 전원 불량', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 전원  불량 발생', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 전원  불량입니다', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 전원  불량인 것 같아요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 전원  문제가 있어요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 보스 찢어짐', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전 표시등 오류', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 작동 안됨', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러시 마모', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '솔 파손', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '플라스틱 커버 파손', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전 시간 지연', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 호스 갈라짐', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 빨간불', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 나오다가 안 나옴', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 나오다가 안 나와요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 나오다가 안 나오면은', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 나오다가 안 나오고', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 나오다가 안 나오더니', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 나오다가 안 나와', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '솔레노이드 밸브 고장', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽에서 물 누수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽에서 물  누수 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽에서 물 물이 새요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽에서 물 물이 뚝뚝 떨어져요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽에서 물 물이 찌익 새요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 물 미출수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세수 필터 막힘', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세수 필터  막혔어요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세수 필터  막히면', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '세수 필터  막혀서 안 돼요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '카본 브러쉬 마모', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 수명 초과 의심', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 모터 작동', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 충전 오류', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '물이 안 빨려요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수탱크 필터 막힘', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수탱크 필터  막혔어요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수탱크 필터  막히면', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수탱크 필터  막혀서 안 돼요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입력 없음', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 연결 오류', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 떠있음', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 탈착 불가', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 탈착 가 안 돼요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 탈착  안 됨', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 탈착  안 됨니다', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '패드 탈착  안 될 때', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 닿지 않음', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 용량 불일치', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 한쪽에서 물 안 나옴', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 한쪽에서 물 안 나와요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 한쪽에서 물 안 나오면은', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 한쪽에서 물 안 나오고', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 한쪽에서 물 안 나오더니', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 한쪽에서 물 안 나와', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 라인 막힘', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 라인  막혔어요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 라인  막히면', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 라인  막혀서 안 돼요', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '홈 파손', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '먼지 흡입 불량', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '먼지 흡입  불량 발생', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '먼지 흡입  불량입니다', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '먼지 흡입  불량인 것 같아요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '먼지 흡입  문제가 있어요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', 'S7 장비 시동 불가', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', 'S7 장비 시동 가 안 돼요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', 'S7 장비 시동  안 됨', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', 'S7 장비 시동  안 됨니다', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', 'S7 장비 시동  안 될 때', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 빠짐 불량', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 빠짐  불량 발생', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 빠짐  불량입니다', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 빠짐  불량인 것 같아요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 빠짐  문제가 있어요', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '수납함 파손', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '고무 패드 빠짐', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 잔량 부족', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 교체 이력', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 표시 오류', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '바퀴 손상', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '폐수 흡입 불량', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '폐수 흡입  불량 발생', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '폐수 흡입  불량입니다', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '폐수 흡입  불량인 것 같아요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '폐수 흡입  문제가 있어요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 교체 시기 도래', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 표시등 깜빡임', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 작동 불능', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 0 표시', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 조전압', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '폐수통 미충전', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전 표시 오류', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '한쪽 흡입 불량', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '한쪽 흡입  불량 발생', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '한쪽 흡입  불량입니다', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '한쪽 흡입  불량인 것 같아요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '한쪽 흡입  문제가 있어요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 문제 가능성', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '물 빨아들이기 어려움', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '흡입 모터 에러', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 작동 불량', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 작동  불량 발생', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 작동  불량입니다', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 작동  불량인 것 같아요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 모터 작동  문제가 있어요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물이 많이 새는 현상', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 인식 불가', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 인식 가 안 돼요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 인식  안 됨', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 인식  안 됨니다', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 인식  안 될 때', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수 호스 누수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수 호스  누수 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수 호스 물이 새요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수 호스 물이 뚝뚝 떨어져요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '폐수 호스 물이 찌익 새요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 방치', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 교체 어려움', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '에러코드 3-5 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '솔레노이드 밸브 이상', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전기 문제 가능성', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '물 분사 정상', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '물 흡입 불능', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 빨간불 깜빡임', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '에러코드 2-5 발생', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 교체 이력 확인', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 깜빡거림', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '가이드 롤러 파손', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '스키지 한쪽 흡입 불량', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '스키지 한쪽 흡입  불량 발생', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '스키지 한쪽 흡입  불량입니다', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '스키지 한쪽 흡입  불량인 것 같아요', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '스키지 한쪽 흡입  문제가 있어요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '사이드 브러쉬 작동 불능', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '고무판 파손', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '전자밸브 고장 가능성', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '필터 누수', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '필터  누수 발생', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '필터 물이 새요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '필터 물이 뚝뚝 떨어져요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '필터 물이 찌익 새요', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '조전압', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽 물 안 나옴', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽 물 안 나와요', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽 물 안 나오면은', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽 물 안 나오고', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽 물 안 나오더니', 'ground_truth_mined', 2),
('WATER_SOLENOID', '급수/세제계통', '브러쉬 쪽 물 안 나와', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '충전 시간 증가', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '브러쉬 내려오지 않음', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '앞뒤 주행 불가', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '앞뒤 주행 가 안 돼요', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '앞뒤 주행  안 됨', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '앞뒤 주행  안 됨니다', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '앞뒤 주행  안 될 때', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '작동 중 꺼짐', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '전원 깜빡임', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '전후진 불능', 'ground_truth_mined', 2),
('CHASSIS', '외관/섀시/바디', '경첩 파손', 'ground_truth_mined', 2),
('POWER', '배터리/전원계통', '배터리 전원 미인식', 'ground_truth_mined', 2),
('DRIVE_BRUSH', '브러시/구동계통', '볼트 헛돌림', 'ground_truth_mined', 2),
('SUCTION', '흡입계통', '빨아들이고', 'counselor_manual', 100),
('SUCTION', '흡입계통', '빨아들이면은', 'counselor_manual', 100),
('SUCTION', '흡입계통', '빨아들이질 않음', 'counselor_manual', 100),
('SUCTION', '흡입계통', '물을 못 빨아들임', 'counselor_manual', 100),
('SUCTION', '흡입계통', '바닥에 물이 흥건함', 'counselor_manual', 100),
('SUCTION', '흡입계통', '물을 못 당겨요', 'counselor_manual', 100),
('SUCTION', '흡입계통', '웽웽거리는 모터 소음', 'counselor_manual', 100),
('SUCTION', '흡입계통', '모터에서 탄내 남', 'counselor_manual', 100),
('SUCTION', '흡입계통', '흡입이 안 먹혀요', 'counselor_manual', 100),
('SUCTION', '흡입계통', '물이 그대로 남아있음', 'counselor_manual', 100)
ON CONFLICT (part_code, phrase) DO UPDATE SET 
    frequency_count = EXCLUDED.frequency_count,
    is_active = true;

COMMIT;
