"""Initial schema

Revision ID: 1f41ee9b8913
Revises: 
Create Date: 2026-08-23 15:14:46.361489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f41ee9b8913'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('sales_type', sa.String(length=50), nullable=True),
    sa.Column('sales_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_price', sa.Integer(), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_codes',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('parts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('compatible_models', sa.String(length=200), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expected_lifespan', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_inquiries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inquiry_type', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('manager', sa.String(length=50), nullable=True),
    sa.Column('manager_phone', sa.String(length=20), nullable=True),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('history_type', sa.String(length=50), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('used_part_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['used_part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log_minimal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consult_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('manager', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=True),
    sa.Column('is_visit_required', sa.Boolean(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager', sa.String(length=50), nullable=True),
    sa.Column('manager_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('address_detail', sa.String(length=200), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('part_code', sa.String(length=40), nullable=False),
    sa.Column('category_l1', sa.Text(), nullable=False),
    sa.Column('category_l2', sa.Text(), nullable=True),
    sa.Column('action_category', sa.Text(), nullable=False),
    sa.Column('action_detail', sa.Text(), nullable=False),
    sa.Column('action_script', sa.Text(), nullable=True),
    sa.Column('cost_type', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('source_engine', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['part_codes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consult_id', sa.UUID(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('matched_keyword', sa.Text(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consult_id'], ['consult_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consult_keywords',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consult_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['consult_id'], ['consult_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consult_id', sa.UUID(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['consult_id'], ['consult_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('manager', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('address_detail', sa.String(length=200), nullable=True),
    sa.Column('consult_id', sa.UUID(), nullable=True),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consult_id'], ['consult_logs.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_parts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Text(), nullable=True),
    sa.Column('new_status', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_status_history')
    op.drop_table('visit_parts')
    op.drop_table('visits')
    op.drop_table('llm_logs')
    op.drop_table('consult_keywords')
    op.drop_table('classification_attempts')
    op.drop_table('symptom_rules')
    op.drop_table('customers')
    op.drop_table('consult_logs')
    op.drop_table('audit_log_minimal')
    op.drop_table('asset_history')
    op.drop_table('sales_inquiries')
    op.drop_table('parts')
    op.drop_table('part_codes')
    op.drop_table('employees')
    op.drop_table('assets')
    # ### end Alembic commands ###
