"""add unique constraint to symptom_rules

Revision ID: 592f319e9774
Revises: 1f41ee9b8913
Create Date: 2026-08-23 15:31:50.449567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592f319e9774'
down_revision: Union[str, Sequence[str], None] = '1f41ee9b8913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sr_keyword_gin'), table_name='symptom_rules', postgresql_using='gin')
    op.drop_index(op.f('idx_sr_keyword_trgm'), table_name='symptom_rules', postgresql_using='gin')
    op.create_unique_constraint('uq_keyword_part_code', 'symptom_rules', ['keyword', 'part_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_keyword_part_code', 'symptom_rules', type_='unique')
    op.create_index(op.f('idx_sr_keyword_trgm'), 'symptom_rules', ['keyword'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_sr_keyword_gin'), 'symptom_rules', [sa.literal_column("to_tsvector('simple'::regconfig, keyword)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
